# Generated by Django 5.1.2 on 2024-12-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='list_apps', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('tecno', models.TextField(verbose_name='Técnologías')),
                ('url', models.CharField(max_length=100, verbose_name='Dirección web')),
                ('githud', models.BooleanField(verbose_name='Githud')),
                ('githud_url', models.CharField(max_length=100, verbose_name='Public')),
            ],
            options={
                'verbose_name': 'ListApp',
                'verbose_name_plural': 'ListApps',
                'ordering': ['-created'],
            },
        ),
    ]
