# Generated by Django 5.1.2 on 2024-12-18 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyect',
            options={'verbose_name': 'Juego', 'verbose_name_plural': 'Juegos'},
        ),
    ]
