# Generated by Django 5.1.2 on 2024-12-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created'], 'verbose_name': 'Platillo', 'verbose_name_plural': 'Platillos'},
        ),
    ]
